notifications:
  webhooks:
    - https://webhook.commit-email.info/
sudo: false
language: ruby
rvm:
  - 2.4.3
  - 2.5.0
  - 2.6.0
before_install: gem install bundler
script:
  - bundle exec ruby test/run_test.rb
